// import "./Course/looops/countNegative.js"
// import "./Course/looops/searchAnElem.js"
// import "./Course/looops/findLargest.js"
// import "./Course/looops/findSmallest.js"
// import "./Course/looops/findSecondLargest.js"
// import "./Course/Patterns/pattern1.js"
// import "./Course/Patterns/pattern2.js"
// import "./Course/Patterns/pattern3.js"
import "./Course/Patterns/pattern4.js"